name: "Terragrunt plan STAGING"

concurrency:
  group: terragrunt-staging
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main
    paths:
      - "terragrunt/aws/**"
      - "terragrunt/env/staging/**"
      - "terragrunt/env/common/**"
      - "terragrunt/env/root.hcl"
      - ".github/workflows/terragrunt-plan-staging.yml"

env:
  AWS_REGION: ca-central-1
  TF_INPUT: false
  TF_VAR_cloudwatch_alarm_slack_webhook: ${{ secrets.STAGING_SLACK_WEBHOOK_OPS }}
  TF_VAR_freshdesk_api_key: ${{ secrets.STAGING_FRESHDESK_API_KEY }}
  TF_VAR_airtable_api_key: ${{ secrets.STAGING_AIRTABLE_API_KEY }}
  TF_VAR_airtable_base_id: ${{ secrets.STAGING_AIRTABLE_BASE_ID }}
  TF_VAR_airtable_table_name_clients: ${{ secrets.STAGING_AIRTABLE_TABLE_NAME_CLIENTS }}
  TF_VAR_airtable_table_name_teams: ${{ secrets.STAGING_AIRTABLE_TABLE_NAME_TEAMS }}
  TF_VAR_airtable_table_name_services: ${{ secrets.STAGING_AIRTABLE_TABLE_NAME_SERVICES }}
  TF_VAR_gcp_project_number: ${{ secrets.GCP_PROJECT_NUMBER }}
  TF_VAR_gcp_pool_id: ${{ secrets.GCP_POOL_ID }}
  TF_VAR_gcp_provider_id: ${{ secrets.STAGING_GCP_PROVIDER_ID }}
  TF_VAR_gcp_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  TF_VAR_gcp_ga_property_forms_marketing_site: ${{ secrets.GCP_GA_PROPERTY_FORMS_MARKETING_SITE }}
  TF_VAR_gcp_ga_property_notification_ga4: ${{ secrets.GCP_GA_PROPERTY_NOTIFICATION_GA4 }}
  TF_VAR_gcp_ga_property_platform_form_client: ${{ secrets.GCP_GA_PROPERTY_PLATFORM_FORM_CLIENT }}
  TF_VAR_gcp_ga_property_platform_core_superset_doc: ${{ secrets.GCP_GA_PROPERTY_PLATFORM_CORE_SUPERSET_DOC }}
  TF_VAR_qualtrics_external_id: ${{ secrets.QUALTRICS_EXTERNAL_ID }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terragrunt-plan-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@36df0d7572a15921998170395475093c183d720a # v1.3.0
        env:
          CONFTEST_VERSION: 0.36.0 
          CONFTEST_CHECKSUM: d98783276c4fd47c779a1ece4c0decba9ee6462687839d25389882a468c362cc
          TERRAFORM_VERSION: 1.14.8
          TERRAFORM_CHECKSUM: 56a5d12f47cbc1c6bedb8f5426ae7d5df984d1929572c24b56f4c82e9f9bf709
          TERRAGRUNT_VERSION: 0.98.0
          TERRAGRUNT_CHECKSUM: 68a9e029b438957c4164e505dfade123c67d6c3c3e11880bcadf3f2b33a8d865
          TF_SUMMARIZE_VERSION: 0.3.5
          TF_SUMMARIZE_CHECKSUM: e0ea7b514f7a57a85e5e4594acdccbf2dce3af7e00fe90580b2ad9cc1288d317
          TRUFFLEHOG_VERSION: 3.90.12
          TRUFFLEHOG_CHECKSUM: 318fd1e8af68b54f4465437208582003a5948293ea401c5c67bb55f17e4e2102

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::454671348950:role/data-lake-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terragrunt plan buckets
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/buckets"
          comment-delete: "true"
          comment-title: "Staging: buckets 🪣"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan oidc
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/oidc"
          comment-delete: "true"
          comment-title: "Staging: oidc 🔑"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan glue
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/glue"
          comment-delete: "true"
          comment-title: "Staging: glue 🧴"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan athena
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/athena"
          comment-delete: "true"
          comment-title: "Staging: athena 🦉"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan alarms
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/alarms"
          comment-delete: "true"
          comment-title: "Staging: alarms 🚨"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan export
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/export"
          comment-delete: "true"
          comment-title: "Staging: export 💾"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan stepfunctions
        uses: cds-snc/terraform-plan@19444f6b6243b20d4c89a02f8277f1f6bfbd7915 # v5.0.3
        with:
          directory: "terragrunt/env/staging/stepfunctions"
          comment-delete: "true"
          comment-title: "Staging: stepfunctions 🤖"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"