name: Workflow failure

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      workflow_url:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID:
        required: true
      LOG_ANALYTICS_WORKSPACE_KEY:
        required: true
      STAGING_SLACK_WEBHOOK_OPS:
        required: true
      PRODUCTION_SLACK_WEBHOOK_OPS:
        required: true

jobs:
  on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@9ad793100229573be3f5ba78cc69ec523f2c8b7e # v1.1.0
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
          DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
          DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
          DNS_PROXY_WILDCARDGREEDY: "true"

      - name: Determine target ops channel
        run: |
          ENVIRONMENT_LOWER="$(echo "${{ inputs.environment }}" | tr '[:upper:]' '[:lower:]')"
          if [[ "$ENVIRONMENT_LOWER" == *"staging"* ]]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.STAGING_SLACK_WEBHOOK_OPS }}" >> $GITHUB_ENV
          else
            echo "SLACK_WEBHOOK_URL=${{ secrets.PRODUCTION_SLACK_WEBHOOK_OPS }}" >> $GITHUB_ENV
          fi

      - name: Notify Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Data Lake workflow failed: <${{ inputs.workflow_url }}|${{ inputs.workflow_name }}>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" "$SLACK_WEBHOOK_URL"
