name: Workflow failure

on:
  workflow_run:
    workflows:
      - "Docker build, push and deploy Production"
      - "Docker build, push and deploy Staging"
      - "Glue Job Sync"
      - "Terragrunt apply PRODUCTION"
      - "Terragrunt apply STAGING"
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Determine target ops channel
        run: |
          WORKFLOW_NAME_LOWER="$(echo ${{ github.event.workflow_run.name }} | tr '[:upper:]' '[:lower:]')"
          if [[ "$WORKFLOW_NAME_LOWER" == *"staging"* ]]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.STAGING_SLACK_WEBHOOK_OPS }}" >> $GITHUB_ENV
          else
            echo "SLACK_WEBHOOK_URL=${{ secrets.PRODUCTION_SLACK_WEBHOOK_OPS }}" >> $GITHUB_ENV
          fi

      - name: Notify Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Data Lake workflow failed: <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow.name }}>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ env.SLACK_WEBHOOK_URL }}
